files: (^section-09-differential-testing/model-package/differential_tests|^section-09-differential-testing/model-package/tests|^\.github/)
repos:
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    additional_dependencies:
      - toml

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  -   id: flake8
      args: [
          '--max-line-length=88',
          '--ignore=E203,E501,W503,F722,F821',
          '--select=C,E,F,W,B,B950',
          '--exclude=__init__.py',
          '--application-import-names=nugen',
          '--import-order-style=appnexus'
      ]
      additional_dependencies: [
          flake8-import-order==0.18.1
      ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-ast
  - id: sort-simple-yaml
  - id: check-yaml
  - id: check-json
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: pretty-format-json
    args: ['--autofix', '--indent=4', '--no-ensure-ascii']
  - id: check-added-large-files
