version: 2
# This is where we organize jobs
jobs:

  # Job 1: Run the regression_model tests
  test_regression_model:
    # The directory from where CircleCI must run the commands
    working_directory: ~/project
    # The docker image in which we want we want to run the commands
    docker:
      - image: circleci/python:3.7.2
    # The steps to run as part of this job
    steps:
      - checkout
      - run:
          name: Running tests
          # 1. We create a virtual environnement
          # 2. We activate it
          # 3. We upgrade pip
          # 4. We install the dependencies
          # 5. We set the permissions to allow us to run that script
          # 6. We run the script
          # 7. We unzip the downloaded file
          # 8. We run the regression_model tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            unzip -j "packages/regression_model/regression_model/datasets/house-prices-advanced-regression-techniques" "*.csv" -d "packages/regression_model/regression_model/datasets/"
            py.test -vv packages/regression_model/tests
  
  # Job 2: Run the ml_api tests
  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/ml_api/tests
  
  # Job 3: Automate training and publishing the model      
  train_and_upload_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: 
          name: Setup env
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r packages/regression_model/requirements.txt
      - run: 
          name: Publish model
          # 1. We activate the virtual environment
          # 2. We set the permissions to allow us to run that script
          # 3. We run the script
          # 4. We set the PYTHONPATH to train the model
          # 5. We run the script to upload the model
          command: |
            . venv/bin/activate
            chmod +x ./scripts/fetch_kaggle_dataset.sh ./scripts/publish_model.sh
            ./scripts/fetch_kaggle_dataset.sh
            unzip -j "packages/regression_model/regression_model/datasets/house-prices-advanced-regression-techniques" "*.csv" -d "packages/regression_model/regression_model/datasets/"
            PYTHONPATH=./packages/regression_model python3 packages/regression_model/regression_model/train_pipeline.py
            ./scripts/publish_model.sh ./packages/regression_model/


workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - train_and_upload_regression_model
      # For the very first time we run these job, it's required to first train the model before testing it
      - test_ml_api:
          requires:
            - train_and_upload_regression_model
